DELETE FROM consumidor WHERE;
DELETE FROM consumidor WHERE;
DELETE FROM consumidor WHERE;

DELETE FROM atendente WHERE;
DELETE FROM atendente WHERE;
DELETE FROM atendente WHERE;

DELETE FROM contato WHERE;
DELETE FROM contato WHERE;
DELETE FROM contato WHERE;
